### ISSUE TITLE
判定“飞机”牌型时出错

### ISSUE THREAD

**Issue by HaozhengLi** [FinixLei/WeChat_LandLords#2]
Python版本虽然报错，但程序能强行往下跑；C++版本报错，就终止了。

Python测试用例：
```
lorder_cards = '3 3 3 4 4 4 5 6'
farmer_cards = '3 4 5 6'
```

Python报错情况：
```
可输入的命令:
pass - 过，不出牌
quit - 立即退出程序
------------------------------
初始状态: 
地主家的牌: ['3', '3', '3', '4', '4', '4', '5', '6']
农民家的牌: ['3', '4', '5', '6']
当前出牌者: 地主
--------------------
18 Moves totally: [['3', '3', '3', '4', '4', '4', '5', '6'], ['3', '3', '3', '4', '4', '4'], ['3', '3', '3', '4', '4'], ['3', '3', '4', '4', '4'], ['3', '3', '3', '4'], ['3', '3', '3', '5'], ['3', '3', '3', '6'], ['3', '4', '4', '4'], ['4', '4', '4', '5'], ['4', '4', '4', '6'], ['3', '3', '3'], ['4', '4', '4'], ['3', '3'], ['4', '4'], ['3'], ['4'], ['5'], ['6']]
Move: ['3', '3', '3', '4', '4', '4', '5', '6']; Score: 100; calculated 1 nodes 
Calc Time: 0.00 seconds
Process Process-3:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "E:\Output\Python_output\CCP\WeChat_LandLords\Python\utils.py", line 56, in wrapper
    result = fn(*args, **kw)
  File "E:\Output\Python_output\CCP\WeChat_LandLords\Python\minmax_engine.py", line 18, in process_search
    score = minmax_search(result_dict, lorder_cards, farmer_cards, current_move, next_player)
  File "E:\Output\Python_output\CCP\WeChat_LandLords\Python\minmax_engine.py", line 54, in minmax_search
    all_moves = get_resp_moves(farmer_cards, current_move)
  File "E:\Output\Python_output\CCP\WeChat_LandLords\Python\move_player.py", line 83, in get_resp_moves
    raise Exception("Unknown Move Type! - %s" % rival_move)
Exception: Unknown Move Type! - [3, 3, 3, 4, 4, 4]
Process Process-19:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "E:\Output\Python_output\CCP\WeChat_LandLords\Python\utils.py", line 56, in wrapper
    result = fn(*args, **kw)
  File "E:\Output\Python_output\CCP\WeChat_LandLords\Python\minmax_engine.py", line 18, in process_search
    score = minmax_search(result_dict, lorder_cards, farmer_cards, current_move, next_player)
  File "E:\Output\Python_output\CCP\WeChat_LandLords\Python\minmax_engine.py", line 63, in minmax_search
    'lorder')
  File "E:\Output\Python_output\CCP\WeChat_LandLords\Python\minmax_engine.py", line 81, in minmax_search
    'farmer')
  File "E:\Output\Python_output\CCP\WeChat_LandLords\Python\minmax_engine.py", line 54, in minmax_search
    all_moves = get_resp_moves(farmer_cards, current_move)
  File "E:\Output\Python_output\CCP\WeChat_LandLords\Python\move_player.py", line 83, in get_resp_moves
    raise Exception("Unknown Move Type! - %s" % rival_move)
Exception: Unknown Move Type! - [3, 3, 3, 4, 4, 4]
Calc Time: 3.38 seconds
地主出牌: ['3', '3', '3', '4', '4', '4', '5', '6']
地主胜利!
```

请求解答，万分感谢！

**Comment by okman334** [comment]
这个问题在第MoveClassifier.hpp的第138行之前加上这句：           else if (count_dict[3] == 2) return {TYPE_10_SERIAL_TRIPLE, -1};
应该能解决。牌型没有判断333444这种没有带翅膀的飞机。

**Comment by FinixLei** [comment]
> 这个问题在第MoveClassifier.hpp的第138行之前加上这句： else if (count_dict[3] == 2) return {TYPE_10_SERIAL_TRIPLE, -1};
> 应该能解决。牌型没有判断333444这种没有带翅膀的飞机。

应该不是这个原因。单线程跑是没有问题的；只有多线程跑有问题。
另外，333444这么基础的牌型，UT早就有了。

**Comment by okman334** [comment]
> > 这个问题在第MoveClassifier.hpp的第138行之前加上这句： else if (count_dict[3] == 2) return {TYPE_10_SERIAL_TRIPLE, -1};
> > 应该能解决。牌型没有判断333444这种没有带翅膀的飞机。
> 
> 应该不是这个原因。单线程跑是没有问题的；只有多线程跑有问题。
> 另外，333444这么基础的牌型，UT早就有了。

但看堆栈确实是崩溃在牌型判断。我加了这个判断之后，多线程版本也跑过了。

**Comment by FinixLei** [comment]
> > > 这个问题在第MoveClassifier.hpp的第138行之前加上这句： else if (count_dict[3] == 2) return {TYPE_10_SERIAL_TRIPLE, -1};
> > > 应该能解决。牌型没有判断333444这种没有带翅膀的飞机。
> > 
> > 
> > 应该不是这个原因。单线程跑是没有问题的；只有多线程跑有问题。
> > 另外，333444这么基础的牌型，UT早就有了。
> 
> 但看堆栈确实是崩溃在牌型判断。我加了这个判断之后，多线程版本也跑过了。

你说的对。我用gdb看了一下，确实是没有 333444的牌型，所以抛了异常。不过我想起来了，这是因为微信斗地主里确实不支持 333444 这样的牌型。所以，应该是在生成招法的时候，可以生成333444555这样的招法以及33344456和3334445566这样的招法，但不能生成333444这样的招法。

**Comment by FinixLei** [comment]
亲自去玩了几把欢乐斗地主，发现333444这样的牌型还是支持的。所以你的修改是正确的。不用动招法生成函数，还是应该动MoveClassifier.hpp.

**Comment by FinixLei** [comment]
It has been fixed.

**Comment by okman334** [comment]
> It has been fixed.

看来程序员都是夜猫子呀。

**Comment by HaozhengLi** [comment]
明白了，感谢二位的帮助！
